import TimerContextProvider from '@/context/timer-context'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pomo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className} style={{ overflow: 'visible' }}>
        <TimerContextProvider>
          <Navbar />
          {children}
        </TimerContextProvider>
      </body>
    </html>
  )
}
